# Generated by Django 4.2.6 on 2023-10-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturerecord',
            name='date',
            field=models.DateTimeField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='temperaturerecord',
            name='timestamp',
            field=models.DateTimeField(default='2020-01-01'),
        ),
    ]
